In [2]:
from get_draws.api import get_draws
from db_queries import get_population

ModuleNotFoundError: No module named 'get_draws'

In [2]:
df = get_draws(gbd_id_type='rei_id',
                 gbd_id=240,
                 source='exposure',
                 year_id=2020,
                 gbd_round_id=7,
                 status='best',
                 location_id = [179],
                 decomp_step = 'iterative')
df

,rei_id,modelable_entity_id,location_id,year_id,age_group_id,sex_id,parameter,measure_id,metric_id,draw_0,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,model_version_id
0,240,8947.0,179,2020,2,1,cat3,5,3,0.206479,...,0.201906,0.207013,0.201623,0.207718,0.203513,0.201013,0.204170,0.205669,0.205070,550808.0
1,240,8947.0,179,2020,3,1,cat3,5,3,0.205927,...,0.206177,0.205521,0.202293,0.197825,0.203642,0.200260,0.204336,0.203150,0.202627,550808.0
2,240,8947.0,179,2020,34,1,cat3,5,3,0.212440,...,0.206180,0.205588,0.212324,0.205710,0.210045,0.208375,0.206595,0.210629,0.211175,550808.0
3,240,8947.0,179,2020,238,1,cat3,5,3,0.227440,...,0.232681,0.233763,0.222279,0.232324,0.225639,0.227074,0.227066,0.220611,0.228048,550808.0
4,240,8947.0,179,2020,388,1,cat3,5,3,0.211991,...,0.208056,0.206800,0.210783,0.209767,0.205127,0.209873,0.213796,0.205402,0.210300,550808.0
5,240,8947.0,179,2020,389,1,cat3,5,3,0.216547,...,0.215384,0.219896,0.222422,0.218237,0.218291,0.215734,0.218041,0.221062,0.219805,550808.0
6,240,8947.0,179,2020,2,2,cat3,5,3,0.201531,...,0.201300,0.203744,0.198064,0.198381,0.201499,0.201124,0.201007,0.201972,0.202921,550808.0
7,240,8947.0,179,2020,3,2,cat3,5,3,0.197719,...,0.199989,0.198529,0.204081,0.199005,0.198962,0.201309,0.203824,0.199634,0.197535,550808.0
8,240,8947.0,179,2020,34,2,cat3,5,3,0.201820,...,0.199433,0.197733,0.200791,0.197678,0.203819,0.197836,0.206163,0.200970,0.198561,550808.0
9,240,8947.0,179,2020,238,2,cat3,5,3,0.208643,...,0.205999,0.206526,0.207682,0.212433,0.214962,0.205684,0.209889,0.206767,0.204881,550808.0
10,240,8947.0,179,2020,388,2,cat3,5,3,0.203476,...,0.202490,0.201467,0.206879,0.204590,0.200847,0.204789,0.206914,0.199679,0.204216,550808.0
11,240,8947.0,179,2020,389,2,cat3,5,3,0.204628,...,0.205613,0.205897,0.199237,0.203319,0.202035,0.202350,0.203647,0.208597,0.201703,550808.0
12,240,8946.0,179,2020,2,1,cat2,5,3,0.099359,...,0.096907,0.096691,0.095860,0.095479,0.100423,0.098267,0.095587,0.095335,0.092165,550817.0
13,240,8946.0,179,2020,3,1,cat2,5,3,0.094726,...,0.093133,0.095609,0.095451,0.096276,0.093727,0.098743,0.094136,0.096417,0.095140,550817.0
14,240,8946.0,179,2020,34,1,cat2,5,3,0.076602,...,0.072606,0.074739,0.072028,0.069317,0.072429,0.072085,0.072371,0.076189,0.071622,550817.0
15,240,8946.0,179,2020,238,1,cat2,5,3,0.093100,...,0.096660,0.092153,0.093167,0.092927,0.095290,0.093621,0.092244,0.093026,0.095709,550817.0
16,240,8946.0,179,2020,388,1,cat2,5,3,0.095582,...,0.098029,0.097297,0.097388,0.099265,0.099780,0.098306,0.097415,0.093937,0.098985,550817.0
17,240,8946.0,179,2020,389,1,cat2,5,3,0.101135,...,0.100815,0.097343,0.098215,0.099755,0.097342,0.101479,0.100135,0.100088,0.101560,550817.0
18,240,8946.0,179,2020,2,2,cat2,5,3,0.081477,...,0.081353,0.082922,0.078335,0.080112,0.079194,0.080033,0.082063,0.080016,0.080716,550817.0
19,240,8946.0,179,2020,3,2,cat2,5,3,0.079337,...,0.083124,0.079043,0.082857,0.078002,0.079144,0.081729,0.078157,0.077337,0.079481,550817.0
20,240,8946.0,179,2020,34,2,cat2,5,3,0.061428,...,0.060229,0.060327,0.062372,0.061874,0.060855,0.059840,0.061944,0.063525,0.061415,550817.0
21,240,8946.0,179,2020,238,2,cat2,5,3,0.073481,...,0.071347,0.075307,0.070966,0.076049,0.075612,0.070145,0.074666,0.071569,0.069435,550817.0
22,240,8946.0,179,2020,388,2,cat2,5,3,0.083955,...,0.081678,0.081470,0.081383,0.086369,0.084274,0.079732,0.083984,0.082802,0.079915,550817.0
23,240,8946.0,179,2020,389,2,cat2,5,3,0.082938,...,0.081722,0.082510,0.078533,0.079605,0.085872,0.081931,0.082490,0.079954,0.083674,550817.0
24,240,8945.0,179,2020,2,1,cat1,5,3,0.040076,...,0.041269,0.038032,0.040314,0.036597,0.044041,0.041816,0.037987,0.036873,0.033778,643433.0
25,240,8945.0,179,2020,3,1,cat1,5,3,0.036672,...,0.034547,0.037485,0.041928,0.041762,0.036610,0.043970,0.037100,0.039512,0.037480,643433.0
26,240,8945.0,179,2020,34,1,cat1,5,3,0.017051,...,0.016060,0.017740,0.013945,0.013766,0.015659,0.015178,0.015976,0.017109,0.014165,643433.0
27,240,8945.0,179,2020,238,1,cat1,5,3,0.026460,...,0.027572,0.024116,0.028167,0.025047,0.029054,0.026302,0.025928,0.028077,0.028423,643433.0
28,240,8945.0,179,2020,388,1,cat1,5,3,0.036031,...,0.037879,0.040208,0.037924,0.040665,0.042395,0.038845,0.036686,0.035337,0.039607,643433.0
29,240,8945.0,179,2020,389,1,cat1,5,3,0.038358,...,0.038136,0.032905,0.034465,0.035860,0.033735,0.039172,0.036273,0.035967,0.035885,643433.0
30,240,8945.0,179,2020,2,2,cat1,5,3,0.023691,...,0.024130,0.024968,0.021893,0.023456,0.021594,0.022247,0.024332,0.021924,0.022793,643433.0
31,240,8945.0,179,2020,3,2,cat1,5,3,0.023077,...,0.025477,0.021779,0.024244,0.021158,0.021827,0.023979,0.020536,0.021021,0.023246,643433.0
32,240,8945.0,179,2020,34,2,cat1,5,3,0.009124,...,0.008853,0.009737,0.010287,0.010228,0.008481,0.008717,0.008485,0.010426,0.010086,643433.0
33,240,8945.0,179,2020,238,2,cat1,5,3,0.015900,...,0.014845,0.017226,0.014151,0.016967,0.016377,0.013973,0.016204,0.015041,0.013582,643433.0
34,240,8945.0,179,2020,388,2,cat1,5,3,0.025132,...,0.023873,0.023774,0.022226,0.027781,0.026536,0.021634,0.024450,0.025827,0.021803,643433.0
35,240,8945.0,179,2020,389,2,cat1,5,3,0.024415,...,0.022936,0.023352,0.022005,0.021503,0.026738,0.023651,0.023913,0.020445,0.025375,643433.0
36,240,NaN,179,2020,2,1,cat4,5,3,0.654086,...,0.659918,0.658264,0.662202,0.660206,0.652022,0.658904,0.662256,0.662122,0.668986,NaN
37,240,NaN,179,2020,3,1,cat4,5,3,0.662675,...,0.666143,0.661385,0.660329,0.664137,0.666020,0.657027,0.664428,0.660921,0.664753,NaN
38,240,NaN,179,2020,34,1,cat4,5,3,0.693907,...,0.705154,0.701932,0.701703,0.711206,0.701868,0.704362,0.705057,0.696073,0.703038,NaN
39,240,NaN,179,2020,238,1,cat4,5,3,0.653000,...,0.643086,0.649969,0.656387,0.649703,0.650017,0.653002,0.654762,0.658286,0.647820,NaN
40,240,NaN,179,2020,388,1,cat4,5,3,0.656396,...,0.656036,0.655695,0.653905,0.650303,0.652698,0.652976,0.652103,0.665324,0.651108,NaN
41,240,NaN,179,2020,389,1,cat4,5,3,0.643960,...,0.645665,0.649856,0.644897,0.646148,0.650632,0.643614,0.645551,0.642883,0.642751,NaN
42,240,NaN,179,2020,2,2,cat4,5,3,0.693301,...,0.693217,0.688366,0.701707,0.698052,0.697713,0.696596,0.692598,0.696089,0.693570,NaN
43,240,NaN,179,2020,3,2,cat4,5,3,0.699867,...,0.691410,0.700648,0.688818,0.701835,0.700067,0.692983,0.697484,0.702007,0.699737,NaN
44,240,NaN,179,2020,34,2,cat4,5,3,0.727628,...,0.731484,0.732203,0.726551,0.730221,0.726845,0.733607,0.723408,0.725079,0.729938,NaN
45,240,NaN,179,2020,238,2,cat4,5,3,0.701975,...,0.707809,0.700941,0.707201,0.694551,0.693049,0.710198,0.699241,0.706623,0.712103,NaN
46,240,NaN,179,2020,388,2,cat4,5,3,0.687437,...,0.691959,0.693290,0.689512,0.681260,0.688344,0.693845,0.684651,0.691692,0.694065,NaN
47,240,NaN,179,2020,389,2,cat4,5,3,0.688019,...,0.689729,0.688241,0.700225,0.695572,0.685355,0.692068,0.689950,0.691005,0.689248,NaN

In [3]:
# filter to the age group IDs needed
age_list = [2,3,34,238,388,389]
df = df.query("age_group_id in @age_list")

In [4]:
# create 2 dataframes that are filtered to the respective parameters
cat1_df = df.query("parameter == 'cat1'").reset_index(drop=True)
cat2_df = df.query("parameter == 'cat2'").reset_index(drop=True)
cat2_df

,rei_id,modelable_entity_id,location_id,year_id,age_group_id,sex_id,parameter,measure_id,metric_id,draw_0,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,model_version_id
0,240,8946.0,179,2020,2,1,cat2,5,3,0.099359,...,0.096907,0.096691,0.095860,0.095479,0.100423,0.098267,0.095587,0.095335,0.092165,550817.0
1,240,8946.0,179,2020,3,1,cat2,5,3,0.094726,...,0.093133,0.095609,0.095451,0.096276,0.093727,0.098743,0.094136,0.096417,0.095140,550817.0
2,240,8946.0,179,2020,34,1,cat2,5,3,0.076602,...,0.072606,0.074739,0.072028,0.069317,0.072429,0.072085,0.072371,0.076189,0.071622,550817.0
3,240,8946.0,179,2020,238,1,cat2,5,3,0.093100,...,0.096660,0.092153,0.093167,0.092927,0.095290,0.093621,0.092244,0.093026,0.095709,550817.0
4,240,8946.0,179,2020,388,1,cat2,5,3,0.095582,...,0.098029,0.097297,0.097388,0.099265,0.099780,0.098306,0.097415,0.093937,0.098985,550817.0
5,240,8946.0,179,2020,389,1,cat2,5,3,0.101135,...,0.100815,0.097343,0.098215,0.099755,0.097342,0.101479,0.100135,0.100088,0.101560,550817.0
6,240,8946.0,179,2020,2,2,cat2,5,3,0.081477,...,0.081353,0.082922,0.078335,0.080112,0.079194,0.080033,0.082063,0.080016,0.080716,550817.0
7,240,8946.0,179,2020,3,2,cat2,5,3,0.079337,...,0.083124,0.079043,0.082857,0.078002,0.079144,0.081729,0.078157,0.077337,0.079481,550817.0
8,240,8946.0,179,2020,34,2,cat2,5,3,0.061428,...,0.060229,0.060327,0.062372,0.061874,0.060855,0.059840,0.061944,0.063525,0.061415,550817.0
9,240,8946.0,179,2020,238,2,cat2,5,3,0.073481,...,0.071347,0.075307,0.070966,0.076049,0.075612,0.070145,0.074666,0.071569,0.069435,550817.0
10,240,8946.0,179,2020,388,2,cat2,5,3,0.083955,...,0.081678,0.081470,0.081383,0.086369,0.084274,0.079732,0.083984,0.082802,0.079915,550817.0
11,240,8946.0,179,2020,389,2,cat2,5,3,0.082938,...,0.081722,0.082510,0.078533,0.079605,0.085872,0.081931,0.082490,0.079954,0.083674,550817.0

In [12]:
# drop the 'parameter' column for each dataframe
cat1_df.drop("parameter", inplace=True, axis=1)
cat2_df.drop("parameter", inplace=True, axis=1)
cat1_df.drop("measure_id", inplace=True, axis =1)
cat2_df.drop("measure_id", inplace=True, axis =1)
cat1_df.drop("metric_id", inplace=True, axis =1)
cat2_df.drop("metric_id", inplace=True, axis =1)

In [13]:
# set the index to all non-draw columns, so that we can add the two dataframes together.
index_list = ["age_group_id", "sex_id", "location_id", "year_id"]
cat1_op_df = cat1_df.set_index(index_list)
cat2_op_df = cat2_df.set_index(index_list)

In [14]:
# add the two operands together
sum_op_df = cat1_op_df + cat2_op_df
sum_op_df

,,,,rei_id,modelable_entity_id,draw_0,draw_1,draw_2,draw_3,draw_4,draw_5,draw_6,draw_7,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,model_version_id
age_group_id,sex_id,location_id,year_id,,,,,,,,,,,,,,,,,,,,,
2,1,179,2020,480,17891.0,0.139436,0.136464,0.143761,0.132579,0.136758,0.136227,0.141764,0.140483,...,0.138177,0.134723,0.136175,0.132076,0.144464,0.140083,0.133574,0.132209,0.125943,1194250.0
3,1,179,2020,480,17891.0,0.131398,0.141506,0.128533,0.132040,0.142831,0.148315,0.136143,0.146309,...,0.127680,0.133093,0.137378,0.138039,0.130337,0.142713,0.131237,0.135929,0.132620,1194250.0
2,2,179,2020,480,17891.0,0.105168,0.097822,0.107398,0.104615,0.099531,0.109892,0.109633,0.095560,...,0.105483,0.107889,0.100229,0.103568,0.100788,0.102280,0.106395,0.101940,0.103509,1194250.0
3,2,179,2020,480,17891.0,0.102414,0.105699,0.106433,0.107103,0.106718,0.103728,0.106689,0.099683,...,0.108601,0.100823,0.107101,0.099160,0.100971,0.105708,0.098693,0.098359,0.102728,1194250.0

In [15]:
# get the population dataframe and set its index so we can multiply with sum.
pop_df = get_population(age_group_id=[235, 2, 3, 4, 5], location_id=179, year_id=2020, gbd_round_id=7, decomp_step = 'iterative')
pop_df.run_id.unique()
pop_df.drop('run_id', inplace = True, axis = 1)

# creating draw_0 through draw_1000 with same population estimate for each value:
for i in range(1000):
     pop_df[f"draw_{i}"] = pop_df["population"]
pop_df.drop("population", axis=1, inplace=True)
pop_df = pop_df.reset_index(drop=True)
pop_op_df = pop_df.set_index(index_list)
pop_op_df

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

,,,,draw_0,draw_1,draw_2,draw_3,draw_4,draw_5,draw_6,draw_7,draw_8,draw_9,...,draw_990,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999
age_group_id,sex_id,location_id,year_id,,,,,,,,,,,,,,,,,,,,,
2,3,179,2020,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,...,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04,6.530348e+04
3,3,179,2020,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,...,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05,1.932161e+05
4,3,179,2020,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,...,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06,3.046784e+06
5,3,179,2020,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,...,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07,1.243741e+07
235,3,179,2020,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,...,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03,6.509103e+03

In [16]:
# multiplying sums and populations
nums_df = (sum_op_df * pop_op_df).reset_index()
nums_df

,age_group_id,sex_id,location_id,year_id,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,...,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,model_version_id,modelable_entity_id,rei_id
0,2,1,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,2,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3,3,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4,3,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5,3,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,235,3,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# sum over age -- group-by all columns except 'age_group_id' and 'draw_x'
group_col_list = ["sex_id", "location_id", "year_id"]
age_sum_nums_df = nums_df.groupby(group_col_list).sum().reset_index().drop("age_group_id", axis=1)
age_sum_pop_df = pop_df.groupby(group_col_list).sum().reset_index().drop("age_group_id", axis=1)

NameError: name 'nums_df' is not defined

In [35]:
# convert back to prevalence rate-space by dividing by aggregate population
age_sum_df = (age_sum_nums_df.set_index(group_col_list) / age_sum_pop_df.set_index(group_col_list)).reset_index()
age_sum_df

,sex_id,location_id,year_id,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,draw_103,...,draw_997,draw_998,draw_999,measure_id,metric_id,model_version_id,modelable_entity_id,population,rei_id,run_id
0,1,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,179,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0

In [ ]:
# take the mean, upper (97.5% percentile), and lower (2.5% percentile) over draws